### ISSUE TITLE
代码学习讨论

### ISSUE THREAD

**Issue by Dengyy** [spartaTeam/stage2#4]
刚刚看了周敏童鞋的代码，在此讨论下：
1.
![image](https://cloud.githubusercontent.com/assets/11731193/14129316/afd488fa-f65b-11e5-8221-165d17a6f697.png)
DOM插入效率的问题，可以考虑一次性插入
推荐文章：
2.
![image](https://cloud.githubusercontent.com/assets/11731193/14129371/217751fe-f65c-11e5-9546-b20af9e7d82e.png)
还未实现
3.
month_arr的构建方式，可以考虑如果不只是1-3月份，如果月份改变，怎样可以改变较少代码实现
4.
![image](https://cloud.githubusercontent.com/assets/11731193/14129399/777012a8-f65c-11e5-9a22-af0b26f42524.png)
nowSelectCity我也更倾向于值为具体城市，因为index来确定选择的城市感觉不是很可靠，要保持<select>和aqiSourceData中顺序一致才行
![image](https://cloud.githubusercontent.com/assets/11731193/14129421/a19681ac-f65c-11e5-95ca-f6004e03a46b.png)
那上面的城市变化就不用index来确定了

**Comment by cherryMo** [comment]
关于4. 我觉得nowSelectCity 是索引和具体城市均可以，页面加载完成后select选项的顺序就确定了，之后渲染图表时根据的也是当前选择的索引的值（也就是城市）确定渲染数据，因此感觉都行。  
另外：week数据月份的开始不是周一，这种情况应该按正常的周数来计算，即周一到周日为一周，不足的只计算剩余的天数的平均值，这个和月份的灵活可以考虑用Date对象的getDay()和getMonth()确定。

**Comment by Dengyy** [comment]
week的想法很好，另外之前忘说了，图中的standard_value是不是应该换成chartData[1][i]？颜色的话应该根据实际值来吧？
![image](https://cloud.githubusercontent.com/assets/11731193/14138461/ee4e685a-f69f-11e5-829b-a9af25391b07.png)

**Comment by echodis** [comment]
[discuss.docx](https://github.com/spartaTeam/stage2/files/195311/discuss.docx)

**Comment by echodis** [comment]
玉莹姐的~：
1.级联操作，已经改好了~
2.我的数据的宽度设置是用css设置的，所以宽度其实是根据数据自动填充的。如果要设置更宽的宽度，必须自动在js中手动设置：比如
 
单独对月份进行设置，是否可行感觉还需要讨论。
我看雅茹的代码是所有的li的宽度都是函数设置的，感觉她的移植性更高
3.月份我考虑的是用天数区分，分为31天，30天和29天，直接在switch case里面添加：
修改以下代码：
 
4.我想的是一次性获取index对应的值，和生成随机数时使用的键名对应，比较直观~感觉都可以啦~
5.standard_value是考虑到设置高度的问题。条件里面给的空气质量正好是0-500，页面显示的高度也是500，然后颜色也设置了5个档，感觉这个出题人比较良心的设计了。satadardtime
是我之前没有看到数据的范围的时候用来数据标准化的变量，现在看来不太必要，因为空气质量的范围原来就到500….（刚才百度了一下…），所以这个我也改过来吧~可以吗？

雅茹的：
关于week的问题我没有考虑到，感觉可以改一下~
雅茹说的getDay() 方法可以，没注意你的代码里面有没有，我看看你的代码然后一起讨论怎么处理~

所以还有两个问题啦：
1.	更改month的宽度
2.	standardtime取消，直接用chartData[1][i]的实际值
3.	周数显示自然周的处理

12修改的话我来就行，今晚可以处理完
3我们再讨论一下怎么改吧~尽量今晚出结果然后在周五之前把这个任务提交吧~~

**Comment by echodis** [comment]
玉莹姐的~：
1.级联操作，已经改好了~
2.我的数据的宽度设置是用css设置的，所以宽度其实是根据数据自动填充的。如果要设置更宽的宽度，必须自动在js中手动设置：比如
![image](https://cloud.githubusercontent.com/assets/12342645/14139557/69bfeff8-f6a6-11e5-9ca3-ae8ce9d8efc3.png)
单独对月份进行设置，是否可行感觉还需要讨论。
我看雅茹的代码是所有的li的宽度都是函数设置的，感觉她的移植性更高

3.月份我考虑的是用天数区分，分为31天，30天和29天，直接在switch case里面添加：
修改以下代码：
![image](https://cloud.githubusercontent.com/assets/12342645/14139577/7d140c92-f6a6-11e5-9da4-408d4ee548c5.png)

4.我想的是一次性获取index对应的值，和生成随机数时使用的键名对应，比较直观~感觉都可以啦~
5.standard_value是考虑到设置高度的问题。条件里面给的空气质量正好是0-500，页面显示的高度也是500，然后颜色也设置了5个档，感觉这个出题人比较良心的设计了。satadardtime
是我之前没有看到数据的范围的时候用来数据标准化的变量，现在看来不太必要，因为空气质量的范围原来就到500….（刚才百度了一下…），所以这个我也改过来吧~可以吗？

雅茹的：
关于week的问题我没有考虑到，感觉可以改一下~
雅茹说的getDay() 方法可以，没注意你的代码里面有没有，我看看你的代码然后一起讨论怎么处理~

所以还有两个问题啦：
**1.    更改month的宽度
2.  standardtime取消，直接用chartData[1][i]的实际值
3.  周数显示自然周的处理**

12修改的话我来就行，今晚可以处理完
3我们再讨论一下怎么改吧~尽量今晚出结果然后在**周五之前**把这个任务提交吧~~

**Comment by echodis** [comment]
问题1，2 ：修改month的宽度，standardtime取消，代码是这样的：
![image](https://cloud.githubusercontent.com/assets/12342645/14141015/0a487b2c-f6af-11e5-97b4-cbf4cfd51f4a.png)

问题3：按自然周处理日期，代码：
![image](https://cloud.githubusercontent.com/assets/12342645/14141055/4349afcc-f6af-11e5-8a03-5ab361de905d.png)

问题三也简化了之前的处理~

你们看看还有什么问题呀
